# Generated by Django 4.2.10 on 2024-10-08 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(choices=[('junior_dev', 'Junior Dev'), ('mid_dev', 'Mid Dev'), ('senior_dev', 'Senior Dev')], default='junior_dev', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('mentor', models.BooleanField(default=False)),
                ('tutor_support', models.CharField(blank=True, choices=[('normal', 'Normal'), ('priority', 'Priority')], max_length=20)),
                ('color', models.CharField(choices=[('orange', 'Orange'), ('green', 'Green'), ('cyan', 'Cyan')], default='orange', max_length=20)),
                ('description', models.TextField(default='Junior Dev monthly subscription package')),
                ('free_delivery', models.BooleanField(default=True)),
                ('product_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('program_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('default_street_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('default_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('default_town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('default_county', models.CharField(blank=True, max_length=80, null=True)),
                ('default_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('moderator', models.BooleanField(default=False)),
                ('active_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_subscription', to='profiles.subscription')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
